Fix tundra.tn.document.attribute transformer services to always return newValues even when the input values list is null or does not exist; this fixes the following exception from being logged by Trading Networks:
    java.lang.Exception: Custom transformation service <service> for
    the attribute <attribute> did not return "newValues" in the
    pipeline.