Fix `tundra.tn.document.attribute:merge` to reformat all existing as well as new attributes that are being saved against the `BizDoc` object to ensure attribute values are in the format expected by the method `BizDocStore.updateAttributes()`.
This works around an issue with webMethods 10.11 where an MWS user-
initiated `BizDoc` route, such as reprocessing a document in MWS,
incorrectly formats `DATETIME` attribute values as Unix milliseconds
string, rather than the expected JDBC datetime string format, which
then causes the following exception to be thrown while routing if the
processing calls `tundra.tn.document.attribute:merge`, which then
calls the method `BizDocStore.updateAttributes()` to save the merged
attribute changes to the database:

    com.wm.app.tn.db.DatastoreException: BizDocStore.updateAttributes
    (0) java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
    at com.wm.app.tn.db.BizDocStore.updateAttributes(BizDocStore.java:703)
    ...